### ISSUE TITLE
Embedding Julia in C++

### ISSUE THREAD

**Issue by KyleKotowick** [alanedelman/18.337_2016#7]
My midterm project requires embedding Julia in some C++ code. I have it mostly working, but the documentation is horrendous and I can't figure out a crucial step. Maybe some of the gurus in the class can help provide some guidance?

I asked this question on the Google Groups page for Julia, so instead of re-writing it all I will link that (and maybe if you answer, answer there so other people can find it one day in the future).

[https://groups.google.com/forum/#!topic/julia-users/TrMvMCZ-_8E](https://groups.google.com/forum/#!topic/julia-users/TrMvMCZ-_8E)

**Comment by alanedelman** [comment]
let me know tomorrow if you don't yet have a satisfactory answer

**Comment by KyleKotowick** [comment]
I received an answer in the Google Groups thread, closing this issue.
