### ISSUE TITLE
Missing UI buttons for Interact.jl

### ISSUE THREAD

**Issue by djsegal** [alanedelman/18.337_2016#9]
Main issue can be seen at: 
  + https://github.com/JuliaLang/Interact.jl/issues/117

Summary: Even after including `Interact.jl` ([PR #8](https://github.com/alanedelman/18.337_2016/pull/8)), I still can't get `@manipulate` to show any buttons. 

----------

note: 
+ I think it's probably a dependency issue (maybe related to the Python 3+ requirement in interact).
+ I just don't know how to get to the bottom of it, now, with all the `IJulia`, `IPython`, `Python`, `Julia`, `Interact`, `ipywidgets` versions floating around my computer now.

**Comment by dpsanders** [comment]
Try
```ENV["Python"] = ""
Pkg.build("IJulia")

```
This will install a local, hopefully working, version of Python and Anaconda inside the `Conda.jl` package directory.
```

**Comment by djsegal** [comment]
Kind of unclear by what you mean.

For example, in my Jupyter Notebook, executing `ENV["Python"]` gives the following error:

```
LoadError: KeyError: key "Python" not found
while loading In[5], in expression starting on line 1

 in access_env(::Base.##339#340, ::String) at ./env.jl:45
 in getindex(::Base.EnvHash, ::String) at ./env.jl:73
 in getindex(::Base.EnvHash, ::String) at /Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib:?
```

I think the empty string assignment you gave might be to resolve conflicting Python versions

---

also, for completeness, here's what gets outputted from `Pkg.build("IJulia")`:

```
INFO: Building Conda
INFO: Building Homebrew
Already up-to-date.
INFO: Building Nettle
INFO: Building ZMQ
INFO: Building IJulia
INFO: Found Jupyter version 4.2.0: jupyter
Writing IJulia kernelspec to /Users/dan/.julia/v0.5/IJulia/deps/julia-0.5/kernel.json ...
Installing julia kernelspec julia-0.5
[InstallKernelSpec] Removing existing kernelspec in /Users/dan/Library/Jupyter/kernels/julia-0.5
[InstallKernelSpec] Installed kernelspec julia-0.5 in /Users/dan/Library/Jupyter/kernels/julia-0.5
```

**Comment by dpsanders** [comment]
Apparently this recently changed to `ENV["JUPYTER"] = ""`. 
You can read more about this in the IJulia.jl README. This is to force a local Jupyter installation, but apparently you already have that since it's using Conda.jl. 

What does `Pkg.build("Interact")` say? Which version of `ipywidgets` do you have? See the Interact.jl README.

**Comment by dpsanders** [comment]
You may need to run the command  

```
jupyter nbextension enable --py --sys-prefix widgetsnbextension
```

using the `jupyter` binary inside the `Conda.jl` package in `~/.julia/v0.5/Conda`?

**Comment by dpsanders** [comment]
Have you done a `Pkg.update()` recently?

**Comment by djsegal** [comment]
`Pkg.build("Interact")` yields:

```
INFO: Building Interact
INFO: Enabling widgetsnbextension
Enabling notebook extension jupyter-js-widgets/extension...
      - Validating: OK
INFO: ipywidgets version found: 5.2.2
INFO: A compatible version of ipywidgets was found. All good.
```

`ENV["JUPYTER"] = ""` led to a very length `Pkg.build("IJulia")`

And I `Pkg.update()` daily. What's the point of life if everything works.

---

But, 
- What do you mean use the `jupyter` binary inside `~/.julia/v0.5/Conda`? 
- Does `jupyter nbextension enable --py --sys-prefix widgetsnbextension` acknowledge where it was called from?

// aside: should we just table this till after class monday?

**Comment by dpsanders** [comment]
I guess that's what `jupyter-js-widgets/extension` in your message from `Pkg.build("Interact")` was. In that case I am out of suggestions about what the problem could be.

**Comment by djsegal** [comment]
I think it was a problem with conda & jupyter-lab. I fixed it with the following steps:
- Remove every Julia/Jupyter package that was installed with **`pip`**
- Reinstall conda using CLI download instead of GUI one
- Reinstall everything again with **`conda`**
- Use `jupyter notebook` instead of `jupyter lab`

---

**edit:** keeping this open till the assignment's due in case anyone else is this dumb

**Comment by djsegal** [comment]
Don't know why this got reopened.

Problem arose from using `jupyter lab`
